/* work-log 日報 (DiaryEntry) — 14件
 * YWT 形式、UNIQUE(user_id, date)
 */
window.MOCK_DIARY_ENTRIES = [
  {
    id: 'd-001',
    date: '2026-05-27', dayOfWeek: '水',
    status: 'draft',
    yatta: '要件定義書 v0.1 をドラフト完了。ER 図と画面遷移を Mermaid で記述。Supabase RLS の方針を整理して付録に記載。',
    wakatta: 'RLS は user_id を auth.uid() に縛るパターンで全テーブル一律でいけそう。社内展開時の admin ロール拡張は別検討で OK。',
    tsugiYaru: '要件レビュー依頼を社内 PM に出す。モックアップ S-04 のドラッグ&ドロップ挙動を検討。',
    tags: ['要件定義', 'Supabase', 'RLS'],
  },
  {
    id: 'd-002',
    date: '2026-05-26', dayOfWeek: '火',
    status: 'published',
    yatta: '8エンティティの確定とドキュメント化。Task / TaskComment / TaskHistory / ChatSession / ChatMessage / DiaryEntry の関係を ER 図にまとめた。',
    wakatta: 'TaskHistory は状態変化のみ記録する設計で、Audit Log の代替も兼ねられる。コメントとの分離が重要。',
    tsugiYaru: 'スキーマ確定。マイグレーション SQL に落とし込む準備をする。',
    tags: ['設計', 'DB'],
  },
  {
    id: 'd-003',
    date: '2026-05-23', dayOfWeek: '土',
    status: 'published',
    yatta: 'Supabase Auth + Google OAuth の動作検証。RLS ポリシーを 3 つ書いて確認 (select / insert / update)。',
    wakatta: 'RLS は auth.uid() = user_id でほぼ全件いける。一部 join 越しの制約は policy USING に書き分けが必要。',
    tsugiYaru: 'ポリシー素案を Notion にまとめる。',
    tags: ['Supabase', 'Auth'],
  },
  {
    id: 'd-004',
    date: '2026-05-22', dayOfWeek: '金',
    status: 'draft',
    yatta: 'UI テンプレ4種 (Metronic / Vuexy×2 / Modernize) を比較。サイドバ・ヘッダ・カードのトーンを実装ベースで確認。',
    wakatta: '管理画面用途では Modernize と Vuexy-Next が候補。MUI のトーンが落ち着いていて提案資料に向く。',
    tsugiYaru: 'Modernize を採用して shared.css にトークンを抜き出す。',
    tags: ['UI', 'デザイン検証'],
  },
  {
    id: 'd-005',
    date: '2026-05-21', dayOfWeek: '木',
    status: 'published',
    yatta: 'ヒアリングシートを完成。10カテゴリ × 平均 8項目で構造化。',
    wakatta: '案件規模に応じて必須/任意を切り替える運用が必要。ハーネスのチェックリストに優先度ラベルを入れる。',
    tsugiYaru: 'ヒアリングを実施して要件抽出のたたきを作る。',
    tags: ['要件定義', 'ヒアリング'],
  },
  {
    id: 'd-006',
    date: '2026-05-20', dayOfWeek: '水',
    status: 'published',
    yatta: '社内ハーネス改善の方針整理。spec-driven-harness の骨子を起こした。',
    wakatta: 'プラグイン形式より、コピー可能なテンプレ + .claude 配下の薄い構成のほうが運用しやすい。',
    tsugiYaru: 'CLAUDE.md と README を書く。',
    tags: ['社内ツール'],
  },
  {
    id: 'd-007',
    date: '2026-05-19', dayOfWeek: '火',
    status: 'published',
    yatta: 'Claude API のキャッシュ機構を Anthropic ドキュメントで再確認。プロンプトキャッシュの TTL 5分を踏まえた設計指針を整理。',
    wakatta: 'cache_control を入れる位置で hit率が大きく変わる。system + tools をキャッシュ境界にするのが定石。',
    tsugiYaru: 'プロンプト構成のテンプレを作る。',
    tags: ['Claude API', '検証'],
  },
  {
    id: 'd-008',
    date: '2026-05-18', dayOfWeek: '月',
    status: 'published',
    yatta: '週次 KPT を実施。先週の Keep / Problem / Try を整理。',
    wakatta: 'AI 壁打ち相手としては YWT のほうが Problem が出やすい (KPT は Problem 抽出が雑になりがち)。',
    tsugiYaru: 'work-log の MVP は YWT、週次/月次サマリに KPT のハイブリッド構成で進める。',
    tags: ['振り返り', 'KPT'],
  },
];
