/* work-log projects (5件) — 要件書 7.2 の Project エンティティ */
window.MOCK_PROJECTS = [
  {
    id: 'pj-001',
    name: 'work-log MVP 開発',
    description: '個人向けタスク管理 + AI 壁打ち日報システムの MVP リリース',
    color: 'primary',
    status: 'active',
    progress: 72,
    taskTotal: 18,
    taskDone: 13,
    owner: 'usr-001',
    createdAt: '2026-04-10',
  },
  {
    id: 'pj-002',
    name: '社内ハーネス改善',
    description: 'Claude Code 社内ハーネスの追加機能 (PDF, モック自動生成)',
    color: 'success',
    status: 'active',
    progress: 45,
    taskTotal: 11,
    taskDone: 5,
    owner: 'usr-001',
    createdAt: '2026-04-22',
  },
  {
    id: 'pj-003',
    name: 'Claude Code 検証',
    description: '各種スキル/エージェント検証、社内ガイドライン整備',
    color: 'warning',
    status: 'active',
    progress: 22,
    taskTotal: 9,
    taskDone: 2,
    owner: 'usr-001',
    createdAt: '2026-05-02',
  },
  {
    id: 'pj-004',
    name: 'UI テンプレ比較レポート',
    description: 'Metronic / Vuexy / Modernize 4テンプレの比較資料',
    color: 'secondary',
    status: 'active',
    progress: 88,
    taskTotal: 8,
    taskDone: 7,
    owner: 'usr-001',
    createdAt: '2026-05-09',
  },
  {
    id: 'pj-005',
    name: 'Q1 業務振り返り',
    description: 'アーカイブ済み Q1(1-3月) 振り返り資料',
    color: 'muted',
    status: 'archived',
    progress: 100,
    taskTotal: 14,
    taskDone: 14,
    owner: 'usr-001',
    createdAt: '2026-01-10',
  },
];
